export const AGENCY_LOGIN_REQUEST = "AGENCY_LOGIN_REQUEST";
export const AGENCY_LOGIN_SUCCESS = "AGENCY_LOGIN_SUCCESS";
export const AGENCY_LOGIN_FAIL = "AGENCY_LOGIN_FAIL";
export const AGENCY_LOGOUT = "AGENCY_LOGOUT";

export const AGENCY_REGISTER_REQUEST = "AGENCY_REGISTER_REQUEST";
export const AGENCY_REGISTER_SUCCESS = "AGENCY_REGISTER_SUCCESS";
export const AGENCY_REGISTER_FAIL = "AGENCY_REGISTER_FAIL";

export const AGENCY_DETAILS_REQUEST = "AGENCY_DETAILS_REQUEST";
export const AGENCY_DETAILS_SUCCESS = "AGENCY_DETAILS_SUCCESS";
export const AGENCY_DETAILS_FAIL = "AGENCY_DETAILS_FAIL";
export const AGENCY_DETAILS_RESET = "AGENCY_DETAILS_RESET";

export const AGENCY_UPDATE_PROFILE_REQUEST = "AGENCY_UPDATE_PROFILE_REQUEST";
export const AGENCY_UPDATE_PROFILE_SUCCESS = "AGENCY_UPDATE_PROFILE_SUCCESS";
export const AGENCY_UPDATE_PROFILE_FAIL = "AGENCY_UPDATE_PROFILE_FAIL";
export const AGENCY_UPDATE_PROFILE_RESET = "AGENCY_UPDATE_PROFILE_RESET";
