export const CAR_LIST_REQUEST = "CAR_LIST_REQUEST";
export const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
export const CAR_LIST_FAILS = "CAR_LIST_FAILS";

export const CAR_ADMIN_REQUEST = "CAR_ADMIN_REQUEST";
export const CAR_ADMIN_SUCCESS = "CAR_ADMIN_SUCCESS";
export const CAR_ADMIN_FAILS = "CAR_ADMIN_FAILS";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";     
export const CAR_DETAILS_FAILS = "CAR_DETAILS_FAILS";

export const DELETE_CAR_REQUEST = "CAR_DETAILS_REQUEST";
export const DELETE_CAR_SUCCESS = "CAR_DETAILS_SUCCESS";
export const DELETE_CAR_FAILS = "CAR_DETAILS_FAILS";


export const CAR_CREATE_REQUEST = "CAR_CREATE_REQUEST";
export const CAR_CREATE_SUCCESS = "CAR_CREATE_SUCCESS";
export const CAR_CREATE_FAILS = "CAR_CREATE_FAILS";
